Retail Lending-Production/src/objects/Bank_Approached__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sourcing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queries&amp;Discrepancies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Solved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Legal Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Queries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Clearance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doc-Kit Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed to Disburse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Disbursal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bank Approached</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Banks Approached</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks Approached</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Co_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant Name (lead)</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Co Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Co Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Co Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salary_gross__c</fullName>
        <label>salary gross</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement Setting</label>
        <referenceTo>Commission_Setting__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Your Contribution for this Stage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Commission_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Payment on Slab Achievement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment With in the Slab Range</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Amount_Paid_on_Inc_Ran__c</fullName>
        <description>These field is used for Incremental slab Range Amount in disbursement and revenue generated</description>
        <inlineHelpText>Amount Paid for slab on Incremental-&gt; Slab Range-&gt;Amount-&gt;Disbursement &amp; Revenue Generated Per 100-?</inlineHelpText>
        <label>Amount Paid on Inc/Ran</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_For_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission For Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commission_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_based_on__c</fullName>
        <inlineHelpText>Commission Based on Eg: &apos;Revenue Generated / Disbursement&apos;</inlineHelpText>
        <label>Commission based on</label>
        <picklist>
            <picklistValues>
                <fullName>Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Generated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commission_paid_on_2__c</fullName>
        <label>Commission paid on basis</label>
        <picklist>
            <picklistValues>
                <fullName>%ge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commission_paid_on__c</fullName>
        <label>Commission paid on</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumulative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incremental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Achievement  Setting</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Company_Financials__c.object
<CustomObject>
    <fields>
        <fullName>Banker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Company Financials (Banker)</relationshipLabel>
        <relationshipName>Company_Financials1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company Financials</label>
    <nameField>
        <label>Company Financials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Disbursement__c.object
<CustomObject>
    <fields>
        <fullName>Disbursement__c</fullName>
        <description>Enter the schedule for disbursement</description>
        <label>Disbursement Schedule</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Disbursement Trackers</relationshipLabel>
        <relationshipName>Disbursement_Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Disbursements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Disbursement Tracker</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Disbursement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/loans__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Borrower</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/PersonalFinancials__c.object
<CustomObject>
    <fields>
        <fullName>Banker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banker</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financials_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financials of</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salary_gross__c</fullName>
        <label>salary gross</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Personal Financials</label>
    <nameField>
        <label>Financial details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Property</relationshipLabel>
        <relationshipName>Property</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/VRTestClass.cls
@isTest
private class VRTestClass {

      static testMethod void b2cLeadConvert() {
        Lead l = new Lead(LastName='Bathula', Status='Followup(FWP)');
        insert l;
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            
            insert c;
        
        Opportunity o = new Opportunity(Name='test',StageName='Disbursed',CloseDate=system.Today(),Borrower__c=c.id);
        insert o;
        Co_Applicant__c ca1 = new Co_Applicant__c(Name='Anil Bathula');
        Co_Applicant__c ca2 = new Co_Applicant__c(Name='Raghu');
        ca1.Lead__c = l.id;
        ca1.Opportunity__c=o.id;
        ca2.Opportunity__c=o.id;
        ca2.Lead__c = l.id;
        insert ca1; insert ca2;
        
        // convert the lead
        Database.LeadConvert lc =
        new database.LeadConvert();        
        lc.setLeadId(l.Id);        
        LeadStatus convertstatus = [select Id, MasterLabel from LeadStatus where IsConverted=
        true limit 1];        
        lc.setConvertedStatus(convertStatus.MasterLabel);        
        Database.LeadConvert[] lcArray =
        new Database.LeadConvert[] {lc};        
        Database.LeadConvertResult[] results = Database.convertLead(lcArray);        
        System.assert(results[0].IsSuccess());
                
    
    }
    
    static testMethod void b2bLeadConvert() {
        Lead l = new Lead(LastName='Bathula', Status='Followup(FWP)', Company='RII');
        insert l;
        Co_Applicant__c ca1 = new Co_Applicant__c(Name='Anil Bathula');
        Co_Applicant__c ca2 = new Co_Applicant__c(Name='Raghu');
        ca1.Lead__c = l.id;
        ca2.Lead__c = l.id;
        insert ca1; insert ca2;
        
        // convert the lead
        Database.LeadConvert lc =
        new database.LeadConvert();        
        lc.setLeadId(l.Id);        
        LeadStatus convertstatus = [select Id, MasterLabel from LeadStatus where IsConverted=
        true limit 1];        
        lc.setConvertedStatus(convertStatus.MasterLabel);        
        Database.LeadConvert[] lcArray =
        new Database.LeadConvert[] {lc};        
        Database.LeadConvertResult[] results = Database.convertLead(lcArray);        
        System.assert(results[0].IsSuccess());
                
    
    }
    //test method for Bank/Comission Setting
    static testMethod void Bank() {
        Account a= new Account(Name='test');
        insert a;
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l =new Loans__c();
        l.Borrower__c=c.id;
        insert l;
        
       
        //Opportunity__c=o.id
        Opportunity o=new Opportunity(Name='test',StageName='Disbursed',CloseDate=System.Today(),
        AccountId=a.id,Loan__c=l.id,borrower__c=c.id);
        Commission_Setting__c cs = new Commission_Setting__c(Name='TestAnil');
        insert cs;
        o.Commission_Setting__c = cs.id;
        insert o;
        
        Bank_Approached__c ba= new Bank_Approached__c(Loan__c=l.id, Opportunity__c=o.id);
        insert ba;
        
        update o;
    }
    
    //test method to update opportunity stage on opportunity from bank approached
    static testMethod void updateOpportunityStage(){
        Account a= new Account(Name='test');
        insert a;
        
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l =new Loans__c();
        l.Borrower__c=c.id;
        insert l;
        
        Opportunity o=new Opportunity(Name='test',  CloseDate=System.Today(),
        AccountId=a.id, StageName='Dumped',borrower__c=c.id);
        insert o;        
        
        o.StageName = 'Audited Appt';
        update o;
        o.StageName = 'Sourcing';
        update o;
        
        Bank_Approached__c ba= new Bank_Approached__c(Opportunity__c=o.id,Loan__c=l.id,
                Approval_Status__c='Sent to Bank');
        insert ba;        
        
        ba.Approval_Status__c ='Logged';
        update ba;
        ba.Approval_Status__c ='Queries&Discrepancies';
        update ba;        
        ba.Approval_Status__c ='Query Solved';
        update ba;        
        ba.Approval_Status__c ='Awaiting Approval';
        update ba;
        ba.Approval_Status__c ='Credit Approved';
        update ba;
        ba.Approval_Status__c ='Awaiting Legal Doc';
        update ba;
        ba.Approval_Status__c ='Legal Queries';
        update ba;
        ba.Approval_Status__c ='Legal Clearance';
        update ba;
        ba.Approval_Status__c ='Valuation';
        update ba;
        ba.Approval_Status__c ='Doc-Kit Signing';
        update ba;
        ba.Approval_Status__c ='Agreed to Disburse';
        update ba;
        ba.Approval_Status__c ='Awaiting Disbursal';
        update ba;
        ba.Approval_Status__c ='Disbursed';
        update ba;
        
       
        
    }
    
    //test method to create personal financials
    static testMethod void  Createfin () {
       
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Contact c= new Contact(LastName='raghu');
        insert c;
        
        Account a= new Account(Name='Res');
        insert a;
        
     /*   PersonalFinancials__c fin = new PersonalFinancials__c(Name='test',Salary_gross__c=1000.00,
        Banker__c=l.Banker_Individuals__c,Financials_of__c=c.Name);
        insert fin;*/
        
    }
    
    //test method for dibursement trigger
    static testMethod void  Disbursement() { 
        
        Account a= new Account(Name='test');
        insert a;
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l=new Loans__c();
        l.Borrower__c=c.id;
        insert l;
        
        Opportunity o=new Opportunity(Name='test',  CloseDate=System.Today(),
        AccountId=a.id,Loan__c=l.id,StageName='Disbursed',borrower__c=c.id);
        insert o; 
        
        Bank_Approached__c b= new Bank_Approached__c(Loan__c=l.id, Opportunity__c=o.id,
        Approval_Status__c='disbursed');       
        insert b;  
        
        Disbursement__c d=new Disbursement__c(Opportunity__c=o.id,loan__c=o.loan__c);        
        insert d;
  
    } 
    
    // test method for creating property trigger 
    static testMethod void  CreateProp() {
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Property__c prop=new Property__c(Name='test');
        insert prop;
    }

    //test method for company financials trigger
    static testMethod void  CreateFinancials() {
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Company_Financials__c cfin=new Company_Financials__c(Name='test'); 
        insert cfin;
    }

    // test method for commissions 
    static testMethod void updateCommissionSet() {
    
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(alias = 'rii1', email='standarduser@testorg.com',
            emailencodingkey='UTF-8', lastname='RII', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id,
            timezonesidkey='America/Los_Angeles', username='rixyncsindiainc@testorg.com');               
            insert u; 
            
        System.runAs(u){
            Commission_Setting__c cs =new Commission_Setting__c(Name='test', Commission_For_User__c=u.id);
            insert cs; 
            
            Commission__c com=new Commission__c(Name='sales',User__c=u.id);        
            insert com;
            
               }
    }
    
    
    static testMethod void commissionUpdate(){
            Commission_Setting__c cs=new Commission_Setting__c(Name='test');            
            insert cs;
     
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            cs.Amount_Paid_on_Inc_Ran__c=1;
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
                      
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
          
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
             
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
             
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
       
     
     }
}