Retail Lending-Production/src/objects/Bank_Approached__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sourcing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queries&amp;Discrepancies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Solved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Legal Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Queries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Clearance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doc-Kit Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed to Disburse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Disbursal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bank Approached</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Banks Approached</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks Approached</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement Setting</label>
        <referenceTo>Commission_Setting__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Your Contribution for this Stage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Commission_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Payment on Slab Achievement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment With in the Slab Range</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commission_For_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission For Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commission_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_based_on__c</fullName>
        <inlineHelpText>Commission Based on Eg: &apos;Revenue Generated / Disbursement&apos;</inlineHelpText>
        <label>Commission based on</label>
        <picklist>
            <picklistValues>
                <fullName>Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Generated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commission_paid_on_2__c</fullName>
        <label>Commission paid on basis</label>
        <picklist>
            <picklistValues>
                <fullName>%ge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Commission_paid_on__c</fullName>
        <label>Commission paid on</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumulative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incremental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Achievement  Setting</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Company_Financials__c.object
<CustomObject>
    <fields>
        <fullName>Banker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Company Financials (Banker)</relationshipLabel>
        <relationshipName>Company_Financials1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company Financials</label>
    <nameField>
        <label>Company Financials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Disbursement__c.object
<CustomObject>
    <fields>
        <fullName>Disbursement__c</fullName>
        <description>Enter the schedule for disbursement</description>
        <label>Disbursement Schedule</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Disbursement Trackers</relationshipLabel>
        <relationshipName>Disbursement_Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Disbursements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Disbursement Tracker</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Disbursement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/loans__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Borrower</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_of_Bank_Approval_Status__c</fullName>
        <description>This Field is created to update the latest stage on loan based on latest stage in Bank approved.</description>
        <label>Max of Bank Approval Status</label>
        <summarizedField>Bank_Approached__c.Status_Number__c</summarizedField>
        <summaryFilterItems>
            <field>Bank_Approached__c.Approval_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected by bank, Rejected by Borrower</value>
        </summaryFilterItems>
        <summaryForeignKey>Bank_Approached__c.Loan__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/PersonalFinancials__c.object
<CustomObject>
    <fields>
        <fullName>Banker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banker</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financials_of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financials of</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salary_gross__c</fullName>
        <label>salary gross</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Personal Financials</label>
    <nameField>
        <label>Financial details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Property</relationshipLabel>
        <relationshipName>Property</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/TriggerTestMethod.cls
@isTest
private class TriggerTestMethod {

    //test method for Bank
    static testMethod void Bank() {
        Account a= new Account(Name='test');
        insert a;
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l =new Loans__c();
        l.borrower__c=c.id;
        insert l;
        
        Opportunity o=new Opportunity(Name='test',StageName='Disbursed',CloseDate=System.Today(),
        AccountId=a.id,Loan__c=l.id,borrower__c=c.id);
        insert o;
        
        Bank_Approached__c ba= new Bank_Approached__c(Loan__c=l.id,Opportunity__c=o.id);
        insert ba;
    }
    
    //test method to update opportunity stage on opportunity from bank approached
    static testMethod void updateOpportunityStage(){
        Account a= new Account(Name='test');
        insert a;
        
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l =new Loans__c();
        l.Borrower__c=c.id;
        insert l;
        
        Opportunity o=new Opportunity(Name='test',  CloseDate=System.Today(),
        AccountId=a.id, StageName='Sourcing',borrower__c=c.id);
        insert o; 
        // do update field that will make Max_of_Bank_Approval_Status__c as 1, 2,,,, 13
        //o.Max_of_Bank_Approval_Status__c=1;
        update o;      
        
        if(o.Max_of_Bank_Approval_Status__c==2){
            o.StageName='Logged'; 
        }      
        
        update o; 
        o.StageName='Queries&Discrepancies';   
        upsert o; 
        
        o.StageName='Query Solved';
        upsert o; 
        
        o.StageName='Awaiting Approval';         
        upsert o; 
        
        o.StageName='Credit Approved';        
        update o;
        
        o.StageName='Awaiting Legal Doc';    
        update o;
        
        o.StageName='Legal Queries';       
        update o;
        
        o.StageName='Legal Clearance';       
        update o;
        
        o.StageName='Valuation';         
        update o;
        
        o.StageName='Doc-Kit Signing';       
        update o;
        
        o.StageName='Agreed to Disburse';        
        update o;
        
        o.StageName='Awaiting Disbursal';         
        update o;
        Bank_Approached__c ba= new Bank_Approached__c(Opportunity__c=o.id,Loan__c=l.id,
                Approval_Status__c='senttobank');
                insert ba;
                if(ba.Approval_Status__c=='1')
                insert ba;
                update o;
        
    }
    
    //test method to create personal financials
    static testMethod void  Createfin () {
       
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Contact c= new Contact(LastName='raghu');
        insert c;
        
        Account a= new Account(Name='Res');
        insert a;
        
       /* PersonalFinancials__c fin = new PersonalFinancials__c(Name='test',Salary_gross__c=1000.00,
        Banker__c=l.Banker_Individuals__c,Financials_of__c=c.Name);
        insert fin;*/
        
    }
    
    //test method for dibursement trigger
    static testMethod void  Disbursement() { 
        
        Account a= new Account(Name='test');
        insert a;
        
        Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
        
        Loans__c l=new Loans__c();
        l.Borrower__c=c.id;
        insert l;
        
        Opportunity o=new Opportunity(Name='test',  CloseDate=System.Today(),
        AccountId=a.id,Loan__c=l.id,StageName='Disbursed',borrower__c=c.Id);
        insert o; 
        
        Bank_Approached__c b= new Bank_Approached__c(Loan__c=l.id, Opportunity__c=o.id,
        Approval_Status__c='disbursed');       
        insert b;  
        
        Disbursement__c d=new Disbursement__c(Loan__c=l.id,Opportunity__c=o.id);
        //Loan__c= oppn.Loan__c;
        insert d;
  
    } 
    
    // test method for creating property trigger 
    static testMethod void  CreateProp() {
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Property__c prop=new Property__c(Name='test');
        insert prop;
    }

    //test method for company financials trigger
    static testMethod void  CreateFinancials() {
        lead l= new lead(LastName='test',Email='abc@gmail.com',Status='Open');
        insert l;
        
        Company_Financials__c cfin=new Company_Financials__c(Name='test'); 
        insert cfin;
    }

    // test method for commissions 
    static testMethod void updateCommissionSet() {
    
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(alias = 'rii1', email='standarduser@testorg.com',
            emailencodingkey='UTF-8', lastname='RII', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id,
            timezonesidkey='America/Los_Angeles', username='rixyncsindiainc@testorg.com');               
            insert u; 
            
        System.runAs(u){
            Commission_Setting__c cs =new Commission_Setting__c(Name='test', Commission_For_User__c=u.id);
            insert cs; 
            
            Commission__c com=new Commission__c(Name='sales',User__c=u.id);        
            insert com;
            
               }
    }
    
    
    static testMethod void commissionUpdate(){
            Commission_Setting__c cs=new Commission_Setting__c(Name='test');            
            insert cs;
     
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Flat Pay';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
                      
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
          
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            cs.Achievement__c='Payment on Slab Achievement';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
             
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Disbursement';
            update cs;
            
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='Amount';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
            
             
            cs.Achievement__c='Payment With in the Slab Range';
            cs.Commission_paid_on__c='Incremental';
            cs.Commission_paid_on_2__c='%ge';
            cs.Commission_based_on__c='Revenue Generated';
            update cs;
       
     
     }
}