Retail Lending-Production/src/objects/Bank_Approached__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sourcing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queries&amp;Discrepancies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query Solved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Legal Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Queries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Clearance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doc-Kit Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed to Disburse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Disbursal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <label>Loan</label>
        <referenceTo>loans__c</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Banks Approached</relationshipLabel>
        <relationshipName>Banks_Approached</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bank Approached</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Banks Approached</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks Approached</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Commission_Setting__c.object
<CustomObject>
    <label>Achievement  Setting</label>
    <nameField>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievement Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/loans__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Borrower</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/Stage2Disbursed_Test.cls
@IsTest

//Test Class for Commission_Setting__c
private class Stage2Disbursed_Test {
    
    static testMethod void stage2(){
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(alias = 'rii1', email='standarduser@testorg.com',        
        emailencodingkey='UTF-8', lastname='RII', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id,timezonesidkey='America/Los_Angeles', username='rixyncsindiainc@testorg.com');
        insert u;  
        
        System.runas(u){
            Account a= new Account(Name='test');
            insert a;
            
            Contact c=New contact();
            c.firstname='asret';
            c.lastname='rest';
            c.accountid=a.id;
            insert c;
                
            Opportunity opp= new Opportunity(Name='Jjjjjjj',AccountId=a.id,CloseDate=System.today(),
                StageName='Agreed to Disburse',Borrower__c=c.id);
            insert opp;         
            
            
            Loans__c l=New loans__c();
            l.name='Test';
            l.opportunity__c=opp.id;
            l.Approval_Status__c='Agreed to Disburse';
            l.Borrower__c=c.id;      
            insert l;
            
            opp.stagename='Disbursed';
            update opp;
            
            Bank_Approached__c ba=new Bank_Approached__c();
            ba.Approval_Status__c='Agreed to Disburse';
            ba.loan__c=l.id;
            ba.Opportunity__c=opp.id;
            insert ba;          
            
          
            }
       
   } 
           
        
}