Retail Lending-Production/src/objects/Comments__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comments</label>
    <nameField>
        <displayFormat>c-{00}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/lcomments_Test.cls
@isTest
public class lcomments_Test{
    public static testmethod void methodname(){
        
       
       
        Lead led = new Lead();
        led.Company = 'Company';
        led.FirstName = 'FirstName';
        led.LastName = 'LastName';
        led.Status='Open';
        led.Email = 'lead11123@testmail.com';
        led.MobilePhone='+91-(0)-9874506789';
        insert led;
        
        Id currleadid=led.id;      
        
        Comments__c c=new Comments__c();        
        c.Lead__c=led.id;
        insert c;
        
        
        PageReference pageRef = Page.leadcomments;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getparameters().put('id',led.id);
        
        ApexPages.StandardController ctrlr=new ApexPages.StandardController(led);
        lcomments ld=new lcomments(ctrlr);
        ld.CustNew();
        ld.CustSave();
        ld.CustEdit();
        ld.custDel();
        ld.CustCancel();        
      
    }
}