Retail Lending-Production/src/objects/Comments__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comments</label>
    <nameField>
        <displayFormat>c-{00}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/opp_comments_Test.cls
@isTest
public class opp_comments_Test{
    public static testmethod void methodname(){    
       
        Account ct = new Account();       
        ct.Name = 'LastName';        
        insert ct;    
        
        Opportunity op=new opportunity();
        op.Name='firstname';
        //op.Contact__c=ct.id;
        op.StageName='Accepted';
        op.CloseDate=System.today();
        insert op;    
        
        Comments__c c=new Comments__c();        
        c.opportunity__c=op.id;
        insert c;
        
        
        PageReference pageRef = Page.Oppcomments;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getparameters().put('id',op.id);
        
        ApexPages.StandardController ctrlr=new ApexPages.StandardController(op);
        opp_comments opp=new opp_comments(ctrlr);
        opp.CustNew();
        opp.CustSave();
        opp.CustEdit();
        opp.custDel();
        opp.CustCancel();        
      
    }
}