Retail Lending-Production/src/objects/Disbursement__c.object
<CustomObject>
    <fields>
        <fullName>Amount_paid_by_Bank__c</fullName>
        <inlineHelpText>The Amount to be Paid by Bank for Parallel Funding</inlineHelpText>
        <label>Amount  paid by Bank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_paid_by_Customer__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Amount to be paid by the Customer for Parallel Funding</inlineHelpText>
        <label>Amount paid by customer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cumulative_Disbursement__c</fullName>
        <label>Cumulative Disbursement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disb_by_Customer_till_date__c</fullName>
        <formula>Opportunity__r.Individual_Contribution_Till_Date__c</formula>
        <label>Disb by Customer till date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursement__c</fullName>
        <description>Enter the schedule for disbursement</description>
        <label>Disbursement Schedule</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disbursement_by_bank__c</fullName>
        <formula>Opportunity__r.Disbursement_By_Bank_Till_Date__c</formula>
        <label>Disbursement by bank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Disbursements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule__c</fullName>
        <label>Payment Schedule</label>
        <picklist>
            <picklistValues>
                <fullName>On Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On start of Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Cellar Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ground Floor Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 1st Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 2nd Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 3rd Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 4th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 5th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 6th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 7th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 8th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 9th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 10th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 11th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 12th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 13th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 14th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 15th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 16th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 17th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 18th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 19th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 20th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 21st Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 22nd Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 23rd Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 24th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On casting of 25th Slab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Completion of Masonry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter the Demanded Amount from the Builder for Disbursement.By default the value in this field will be zero.if you remove it you should put some value or put zero to save record</inlineHelpText>
        <label>Builder Demand</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount1__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Disbursement__c</fullName>
        <description>These calculation for all records which are there for the particular opportunity</description>
        <formula>Amount_paid_by_Bank__c + Amount_paid_by_Customer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount Paid by Bank  + Amount Paid by Customer =Total Disbursement</inlineHelpText>
        <label>Total Disbursement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Disbursment__c</fullName>
        <formula>Opportunity__r.Total_Disbursment_till_Date__c</formula>
        <inlineHelpText>Total Disbursement Till Date adding all the Disbursements which are paid uptill now</inlineHelpText>
        <label>Total Disbursement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Disbursement Tracker</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Disbursement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/Disbursements.cls
public class Disbursements{

    Id oppnId;
    public List<Disbursement__c> disb {get;set;}  
    Decimal cumDisb  {get;set;}
    Decimal  total {get;set;}
    
    public Disbursements() {        
        oppnId = ApexPages.currentPage().getParameters().get('OppnId');
        disb= [Select id, Requested_Amount__c, Amount_paid_by_Customer__c, 
                Amount_paid_by_Bank__c, Total_Disbursement__c, Total_Amount1__c,
                Disb_by_Customer_till_date__c ,Disbursement_by_bank__c,Total_Disbursment__c,
                Payment_Schedule__c, Cumulative_Disbursement__c 
                from Disbursement__c                
                where Opportunity__c=:oppnId]; 
    }
    public PageReference ammendDisb(){
        cumDisb =0;
        total=0;
        for(Disbursement__c d: disb){
            //write logics for disb
       
          cumDisb = cumDisb + d.Total_Disbursement__c;
          d.Cumulative_Disbursement__c = cumDisb;
        
          total=cumDisb*2;     
          d.Total_Amount1__c =total;       
        }
        update disb;        
        PageReference page = new PageReference('/apex/DisbursementVF?OppnId='+oppnId);     
        return page;          
    }  
    public PageReference cancel() {
        return new PageReference('/'+ApexPages.currentPage().getParameters().get('OppnId'));
    }
  public static testMethod void testDisbursemnts(){
        Account a= new Account(Name='Res');
        insert a;
        
        /*Opportunity o=new Opportunity(Name='test',  CloseDate=System.Today(),
        AccountId=a.id,StageName='Disbursed');
        insert o;*/
  
      
      Disbursements dbs=new Disbursements();
      
          dbs.ammendDisb();
         // Disbursement__c disb=new Disbursement__c();
          // disb.Cumulative_Disbursement__c;
          dbs.cancel();
          
  }  
}