Retail Lending-Production/src/objects/Locations__c.object
<CustomObject>
    <label>Locations</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Projects__c.object
<CustomObject>
    <fields>
        <fullName>Builder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Locations__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Towers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Builder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property</relationshipLabel>
        <relationshipName>Property</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Locations__c</referenceTo>
        <relationshipLabel>Property</relationshipLabel>
        <relationshipName>Property</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/VRTestClassII.cls
@isTest
private class VRTestClassII {
     static testMethod void UpdateLoc(){
     
        Account a= new Account(Name='Res');
        insert a;
        
        Locations__c l=new Locations__c(Name='indira Nagar');
        insert l;   
        
        Property__c pr=new Property__c(Name='sunil',Builder_Name__c=a.id,Location__c=l.id);         
        insert pr; 
        
        Projects__c p= new Projects__c(Name='Anil',Property__c=pr.id,Builder_Name__c=pr.Builder_Name__r.id,
                      Location__c=pr.Location__r.id);
        insert p;
        
              
         
        
       }
       
        static testMethod void MatchSpouse(){
            
            Account a= new Account(Name='res');
            Insert a;
            
            Contact c= new Contact(LastName='anil');
            insert c;
            
            Contact cs= new Contact(LastName='rajesh',Spouse__c=c.Id);
            insert cs;
          //  c=[select id,Spouse__c from Contact where Id=: c.Spouse__c];
         //    System.assertEquals('Anil', c.Spouse__r.id);
        
        }
}