Retail Lending-Production/src/objects/Projects__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Towers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <description>Enter the project name</description>
        <inlineHelpText>Enter the project name:Eg:My homes&quot;.</inlineHelpText>
        <label>Tower Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Property</relationshipLabel>
        <relationshipName>Property</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Tower Name</label>
        <referenceTo>Projects__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/Unit_name_on_ctct_Test.cls
@IsTest
private class Unit_name_on_ctct_Test {
     static testMethod void unitName(){
     
     Contact c=new Contact();
     c.Lastname='Anil';
     Insert c;
     
     Contact c1=new Contact();
     c1.Lastname='Anil';
     Insert c1;
     
     
     Property__c p=new property__c();
     p.name ='test';     
     insert p;
     
     Projects__c pj=new Projects__c();
     pj.name='rest';       
     pj.Property__c=p.id;
     insert pj;
     
     Unit__c u=new unit__c();
     u.Project_Name__c=pj.id;
     u.property__c=p.id;
     u.Unit_Owner__c=c.id;
     insert u;
      
     u.Unit_Owner__c=c1.id;
     update u;
     
     delete u;
     }
}