Retail Lending-Production/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Property (Property Owner)</relationshipLabel>
        <relationshipName>Property1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Retail Lending-Production/src/classes/property_owner_ctct_Test.cls
@IsTest
private class property_owner_ctct_Test {
     static testMethod void PropertyName(){
     
     Contact c=new Contact();
     c.Lastname='Anil';
     Insert c;
     
     
     Property__c p=new property__c();
     p.Property_Owner__c=c.id;
     p.name ='test';
     insert p; 
     
     
     Property__c p1=new property__c();
     p1.Property_Owner__c=c.id;
     p1.name ='test1';
     insert p1;     
         
     delete p1;
     delete p;
     }
}